### ISSUE TITLE
How to do fault-localization with cli.jar?

### ISSUE THREAD

**Issue by zhangysh1995** [GZoltar/gzoltar#10]
Hi,

I could run the instrumentation, but cannot find an argument used to run fault-localization with command line. Is there such an argument?

Thank you.

**Comment by jose** [comment]
Hi @zhangysh1995,

I've added a complete usage example for the GZoltar command line interface. You can find it in [here](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.cli.examples).

Let me know if that usage example does not work for you.


--
Best,
Jos

**Comment by zhangysh1995** [comment]
@jose Thanks for your reply. I think it would be better if there is a link from the main page `README` file.
