### ISSUE TITLE
How to interpret the results?

### ISSUE THREAD

**Issue by Kaka727** [GZoltar/gzoltar#13]
Hi Jose,
  Recently, I try the new version 1.7.3 on Defects4J bug Chart-1. Below is the FL result.
![image](https://user-images.githubusercontent.com/33283686/59575395-f8f58680-90ed-11e9-8a26-f76f5de392f8.png)
I know the last two parameters are line number and suspicious. The first one before $ is package. The second one before # is class name. Then, the one before : is method name. Is it right?

But how to interpret results like the 14th line. What's this mean? (int, org.jfree.chart....,boolean)

**Comment by jose** [comment]
Hi @Kaka727,

To distinguish methods with the same name but different type or number of parameters, the fault localization report include, for each method, the type of each argument. 

In detail, the identifier of each line of code follows the following format:
```
package-name$class-name#method-name(type-of-each-argument):line-number
```
For example,
```
org.jfree.chart.plot$CategoryPlot#setRenderer(int, org.jfree.chart.renderer.category.CategoryItemRenderer, boolean):1665
            ^             ^            ^                                        ^                                    ^
      package-name   class-name   method-name                          type-of-each-argument                     line-number
```


--
Best,
Jose

**Comment by Kaka727** [comment]
Thanks Jose. I now understand it!




------------------ Original ------------------

**Comment by wupeng15** [comment]
@jose Hi, I find in the results of Closure-126 there are some outliers like this:
com.google.javascript.rhino$Node$NodeMismatch#Node$NodeMismatch(com.google.javascript.rhino.Node,com.google.javascript.rhino.Node):2163;0.3922322702763681

There are three $ in one line. Why is this?

**Comment by jose** [comment]
@wupeng15, that is because `NodeMismatch` is a static nested class of `Node`:

```java
  63    public class Node implements Cloneable, Serializable {
        // ...
2159      static class NodeMismatch {
2160        final Node nodeA;
2161        final Node nodeB;
2162
2163        NodeMismatch(Node nodeA, Node nodeB) {
        // ...
```

You can find detailed information and examples of different inner classes in java in [here](https://www.geeksforgeeks.org/inner-class-java/).

--
Best,
Jose
