### ISSUE TITLE
executing the  https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.cli.examples

### ISSUE THREAD

**Issue by ssk1216** [GZoltar/gzoltar#18]
### Context
Error is com.gzoltar.cli-1.7.2-jar-with-dependencies.jar does not exist.

### Steps to Reproduce
 **I forked and downloaded the gzoltar from github. From terminal>
> gzoltar-1.7.2/com.gzoltar.cli.examples/ ./run.sh**

 

### Expected behaviour
I was expecting the o/p listed on the  https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.cli.examples

### Environment (please complete the following information, if relevant):
Ubuntu
eclipse Photon

### Additional comments
*Please add any information of interest here below.*

**Comment by ssk1216** [comment]
How can I  invoke Gzoltar from a different Java program ???

**Comment by DehengYang** [comment]
Perhaps you need first to run:
```
cd gzoltar-1.7.2/
mvn clean install
``` 
After that the source code of  `com.gzoltar.cli` will be packaged and saved in `gzoltar-1.7.2/com.gzoltar.cli/target/` as com.gzoltar.cli-1.7.2-SNAPSHOT-jar-with-dependencies.jar.

**Comment by jose** [comment]
> Error is com.gzoltar.cli-1.7.2-jar-with-dependencies.jar does not exist.

@ssk1216, is this still an issue?
