### ISSUE TITLE
Gzoltar integrated with Gitlab CI/CD

### ISSUE THREAD

**Issue by ssk1216** [GZoltar/gzoltar#19]
Any guidelines of how GZoltar can be integrated into Gitlab CI/CD

**Comment by jose** [comment]
Hi @ssk1216,

I do not have a concrete answer for your question as I have never used the [continuous integration system of Gitlab](https://docs.gitlab.com/ee/ci), but I might be able to give you some tips on that.

GZoltar provides a [maven plugin](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.maven) that can be integrated/used in any maven-based project.  Assuming you setup your maven-based project to use GZoltar (please find an example [here](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.maven.examples)), you might be able to run GZoltar from the [Gitlab's continuous integration system](https://docs.gitlab.com/ee/ci).

I hope this helps.

--
Best,
Jose
