### ISSUE TITLE
executing the https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.cli.examples 

### ISSUE THREAD

**Issue by ssk1216** [GZoltar/gzoltar#27]
I am trying to follow the instructions to run the https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.cli.examples 
----------------------------------------------------------------------------------

  /cygdrive/d/gzoltar-master/com.gzoltar.cli.examples

$ ./run.sh

The error is --------
***_*_/c**ygdrive/d/gzoltar-master/com.gzoltar.cli.examples/../com.gzoltar.cli/target/com.gzoltar.cli-1.7.3-SNAPSHOT-jar-with-dependencies.jar does not exist or it is empty! Please go to '/cygdrive/d/gzoltar-master/com.gzoltar.cli.examples/..' and run 'mvn clean install'.**_**_**
-------------------------------------------------------------------------------------------------
When I tried to run 
 mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.081 s
[INFO] Finished           at: 2020-05-13T01:23:32+04:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requi          res a project to execute but there is no POM in this directory (D:\gzoltar-master\com.gzoltar
.cli.examples). Please verify you invoked Maven from the correct directory. -> [Help 1]

What to do here?

**Comment by jose** [comment]
Hi @ssk1216,

As you can see in the error message:

> /cygdrive/d/gzoltar-master/com.gzoltar.cli.examples/../com.gzoltar.cli/target/com.gzoltar.cli-1.7.3-SNAPSHOT-jar-with-dependencies.jar does not exist or it is empty! Please go to '/cygdrive/d/gzoltar-master/com.gzoltar.cli.examples/..' and run 'mvn clean install'.

you must go to `/cygdrive/d/gzoltar-master/com.gzoltar.cli.examples/..` and run `mvn clean install` in that directory. However, you tried to execute `mvn clean install` in the `/cygdrive/d/gzoltar-master/com.gzoltar.cli.examples` directory instead of running it in the `/cygdrive/d/gzoltar-master` directory.


--
Best,
Jose

**Comment by ssk1216** [comment]
Yes It worked. Thanks a lot

**Comment by ssk1216** [comment]
/cygdrive/d/gzoltar-master
$ mvn clean install
.................FAILS .......





ERROR] Failures:
[ERROR]   TestAgentConfigs.testNoPrependAnyVMArguments:204 expected:<-javaagent:[/tmp/]foo=> but was:<-javaagent:[\\tmp\\]foo=>
[ERROR        [m]   TestAgentConfigs.testPrependNullVMArguments:197 expected:<-javaagent:[/tmp/]foo=> but was:<-javaagent:[\\tmp\\]foo=>
[ERROR]   TestAgentConfigs.testPrependVMArguments:210 expected:<-javaagent:[]/tmp/foo=> but was:<-javaagent:[\\tmp\\foo= -javaagent:]/tmp/foo=>
[ERROR]   TestAgentConfigs.testQuotedVMArg                 ument:191 expected:<-javaagent:[/tmp/]foo=> but was:<-javaagent:[\\tmp\\]foo=>
[ERROR]   TestAgentConfigs.testVMArgument:185 expected:<-javaagent:[/tmp/]foo=> but was:<-javaagent:[\tmp\]foo=>
[INFO]
[ERROR] Tests run: 94, Failures: 5, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for root 1.7.3-SNAPSHOT:
[INFO]
[INFO] GZoltar ............................................ SUCCESS [  0.539 s]
[INFO] GZoltar :: Core .................................... FAILURE [  9.079 s]
[INFO] GZoltar :: FL ...................................... SKIPPED
[INFO] GZoltar :: Re          port .................................. SKIPPED
[INFO] GZoltar :: Agent RT ................................ SKIPPED
[INFO] GZoltar :: Agent ................................... SKIPPED
[INFO] GZoltar :: Maven Plugin ............................ SKIPPED
[ [1;34mINFO] GZoltar :: Ant Plugin .............................. SKIPPED
[INFO] GZoltar :: Command Line Interface .................. SKIPPED
[INFO] GZoltar :: Documentation ........................... SKIPPED
[INFO] GZoltar :: Test .................................... SKIPPED
[INFO] GZolta          r :: Distribution ............................ SKIPPED
[INFO] root ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ----              --------------------------------------------------------------------
[INFO] Total time:  9.970 s
[INFO] Finished at: 2020-05-20T23:13:53+04:00
[INFO] ------------------------------------------------------------------------
[ERROR]           Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project com.gzoltar.core: There are test failures.
[ERROR]
[ERROR] Please refer to D:\gzoltar-master\com.gzoltar.core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

**Comment by jose** [comment]
As far I can see, it seems there is an inconsistency between `\` and `/`:
> expected:<-javaagent:[/tmp/]foo=> but was:<-javaagent:[\tmp\]foo=>

It should be OS-dependent, but I see both in your log.  I will investigate this.  (It might take me a while to debug this as I don't have access to a Windows machine right now...)

**Comment by ssk1216** [comment]
I switched to Linux .
