### ISSUE TITLE
Maven plug-in usage example--broken link

### ISSUE THREAD

**Issue by ssk1216** [GZoltar/gzoltar#28]
1. 
When you click on **Maven plug-in usage example,** the page which is displayed is 
https://github.com/GZoltar/gzoltar/tree/master/com.**gzoltar.ant.examples**
Could you please check???

2. Is **gzoltarcli.jar** available with the GZoltar which we download from Github?  

3.  Does the command line version still works on Linux machines??
https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.cli.examples

The Usage section, includes
./run.sh

Is there any other parameter to be added to this statement  ???. 

It doesn't seem to work on my Linux machine.

**Comment by jose** [comment]
Hi @ssk1216,

> When you click on Maven plug-in usage example, the page which is displayed is
> https://github.com/GZoltar/gzoltar/tree/master/com.**gzoltar.ant.examples**
> Could you please check???

Good catch, thanks.  It has been [fixed](https://github.com/GZoltar/gzoltar/commit/bf00ec5d7232bb28c15e54500ab1309eda34a0a2).

> Is gzoltarcli.jar available with the GZoltar which we download from Github?

You can either find it in the [releases page](https://github.com/GZoltar/gzoltar/releases) or create it yourself by compiling the entire project (i.e., `mvn package` in the root directory).

> Does the command line version still works on Linux machines? https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.cli.examples

All GZoltar's plugins have been tested on Linux and MacOS and I can confirm that all plugins work as expected. (Although I have never tried any of the plugins on Windows, they should work on Windows as they do on any other operating system).

> The Usage section, includes
> ./run.sh
> Is there any other parameter to be added to this statement ???.

Yes. [As described in the documentation of the CLI module](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.cli.examples/README.md) the `run.sh` script has two arguments:

- `--instrumentation <online|offline>` (mandatory, use `online` for instrumenting classes at runtime or `offline` for instrumenting classes in a non-runtime way)
- `--help` (optional)

> It doesn't seem to work on my Linux machine.

Could you please provide more details on why it is not working on your machine?



--
Best,
Jose

**Comment by ssk1216** [comment]
gzoltar-master/com.gzoltar.cli.examples$ ./run.sh --instrumentation offline
when I execute the above comment , the error is :
**gzoltar-master/com.gzoltar.cli.examples/lib does not exist!**

**Comment by ssk1216** [comment]
Thanks Jose for the suggestions
I tried to work with the instructions listed on the link:
 https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.maven.examples


/Desktop/GzoltarExperiments/gzoltar-master/com.gzoltar.maven.examples$ mvn clean test- compile

[ERROR] Failed to execute goal on project simple: Could not resolve dependencies for project com.gzoltar.maven.examples:simple:jar:0.0.1-SNAPSHOT: Could not find artifact com.gzoltar:com.gzoltar.cli:jar:1.7.3-SNAPSHOT at specified path

**Comment by jose** [comment]
Hi @ssk1216,

> gzoltar-master/com.gzoltar.cli.examples$ ./run.sh --instrumentation offline when I execute the above comment, the error is: gzoltar-master/com.gzoltar.cli.examples/lib does not exist!
> Same when I try with online instrumentation

[Fixed](https://github.com/GZoltar/gzoltar/commit/ce7dfde09091fc31225b6a33c83ad20b66003a39).

> I tried to work with the instructions listed on the link:
> https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.maven.examples
> 
> /Desktop/GzoltarExperiments/gzoltar-master/com.gzoltar.maven.examples$ mvn clean test-compile
> 
> [ERROR] Failed to execute goal on project simple: Could not resolve dependencies for project com.gzoltar.maven.examples:simple:jar:0.0.1-SNAPSHOT: Could not find artifact com.gzoltar:com.gzoltar.cli:jar:1.7.3-SNAPSHOT at specified path

You first need go to the root directory (in you case `/Desktop/GzoltarExperiments/gzoltar-master/`) and package the GZoltar project, i.e., `mvn package`.  This will insure that all GZoltar's jar files are in the right paths. (I have just [updated](https://github.com/GZoltar/gzoltar/commit/809d2977e692e84d763f28d7bd79ff46f3ca2a96) the documentation to make this a bit more clear)


--
Best,
Jose

**Comment by ssk1216** [comment]
Many Thanks Jose
That was really helpful.
