### ISSUE TITLE
Supported Java Versions

### ISSUE THREAD

**Issue by lapplislazuli** [GZoltar/gzoltar#40]
Good Afternoon, 

I am currently working on a project that uses (old) versions of Gzoltar.
The project is [astor](https://github.com/SpoonLabs/astor). 
In Astor there are multiple jars of the Gzoltar CLI (com.gzoltar-0.0.7, com.gzoltar-0.1.1,com.gzoltar-1.5.1,com.gzoltar-1.6.1-java7) in use, based on the experiment they wanted to reproduce. 

With the maintainer we are investigating to move astor to Java 11, however the available gzoltars fails gracefully above Java 8. 

Do you have a list / overview of which gzoltars work on which java for which java? 

And a bit of an extended question, based on your experience do you think _just using the newest one_ will go smoothly?

**Comment by lapplislazuli** [comment]
If you have some sparetime, 
I'd also be very happy if you have a look at the things I want to migrate. 
The primary method is found [here](https://github.com/lapplislazuli/astor/blob/17174f98c31aedce9dcb6196458664b4b7dd66f0/src/main/java/fr/inria/astor/core/faultlocalization/gzoltar/GZoltarFaultLocalization.java#L193).

It uses `com.gzoltar.core.GZoltar` which ... is old enough to not be in this repository 😄
I feel like most of the configurations that are being done are in [Gzoltars AgentConfigs](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.core/src/main/java/com/gzoltar/core/AgentConfigs.java),
so should I be looking into the Agent(s) of Gzoltar? 

Or is the [FaultLocalizationReport](https://github.com/GZoltar/gzoltar/blob/51967a34817d07fb4d2a9f9c6b193be7089b842d/com.gzoltar.report/src/main/java/com/gzoltar/report/fl/FaultLocalizationReportBuilder.java#L33) more where I want to look? 

In the end to smoothly migrate I need to 

- Set Classes / Paths to execute
- Set Tests to run / exclude Tests
- Get *Statements* and their suspiciousness value
- AFAIK it's run once at program start, but maybe it is run with every alternation of the program

**Comment by jose** [comment]
Hi @lapplislazuli,

> Do you have a list / overview of which gzoltars work on which java for which java?

For the set of versions you mentioned, I've not.  Current official version (i.e., v1.7.2) and current latest version (i.e., v1.7.3-SNAPSHOT) can be used under Java 5, 6, 7, and 8.  (Once pull request [41](https://github.com/GZoltar/gzoltar/pull/41) is merged, you will also be able to use GZoltar under Java >= 9.)

> ... based on your experience do you think just using the newest one will go smoothly?

Current official version (i.e., v1.7.2) and current latest version (i.e., v1.7.3-SNAPSHOT) are the most complete and straightforward versions to use.  But, it always depend on your setup, e.g., whether you're running GZoltar via another Java app or on the command line, whether you're running GZoltar via one of the many GZoltar's plugins.

> The primary method is found [here](https://github.com/lapplislazuli/astor/blob/17174f98c31aedce9dcb6196458664b4b7dd66f0/src/main/java/fr/inria/astor/core/faultlocalization/gzoltar/GZoltarFaultLocalization.java#L193). It uses `com.gzoltar.core.GZoltar` which ... is old enough to not be in this repository 😄

That is indeed super old.  Unless you really need to have backward compatibility or something similar, I would recommend you to port that code to the latest version of GZoltar.  I am happy to help you on that process.

> I feel like most of the configurations that are being done are in [Gzoltars AgentConfigs](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.core/src/main/java/com/gzoltar/core/AgentConfigs.java), so should I be looking into the Agent(s) of Gzoltar?

Kinda.  Do you need to specify/inform GZoltar which classes should be or not be instrumented?  (As of today, by default, all classes loaded by the JVM are instrumented.)  Assuming you do need to specify which classes are instrumented by
GZoltar, you need to setup the [`includes`](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.core/src/main/java/com/gzoltar/core/AgentConfigs.java#L78) and/or [`excludes`](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.core/src/main/java/com/gzoltar/core/AgentConfigs.java#L86) property.

> Or is the [FaultLocalizationReport](https://github.com/GZoltar/gzoltar/blob/51967a34817d07fb4d2a9f9c6b193be7089b842d/com.gzoltar.report/src/main/java/com/gzoltar/report/fl/FaultLocalizationReportBuilder.java#L33) more where I want to look?

Unless you need to compute the suspiciousness score at other granularity than 'line', or to compute the suspiciousness score using some fancy formula than 'ochiai', or even to generate a HTML fault localization report rather than a TXT-based report, you only need to inform GZoltar's Fault Localization Report of three key aspects:
- Where are .class files
- Where is the `gzoltar.ser` file (a binary file generated by GZoltar's Agent when it runs the project's test cases)
- Where do you want the fault localization report to be written

> In the end to smoothly migrate I need to
> - Set Classes / Paths to execute
> - Set Tests to run / exclude Tests
> - Get Statements and their suspiciousness value
> - AFAIK it's run once at program start, but maybe it is run with every alternation of the program

I would recommend you to have a look at [this example](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.cli.examples/run.sh#L112) which exercises exactly the features you need.  (Please ignore the `"$INSTRUMENTATION" == "offline"` parts which I believe you won't need.)


--
Best,
Jose

**Comment by lapplislazuli** [comment]
@jose thanks for the elaborate answer and the offer for help 👍 

I have been looking into the shell example starting from the patch in #41, 
and I think I get most of what is happening. 
Just a few questions remain: 

- the instrumentation is done on .class files and .class-files only? Does it need to instrument the tests too?
- is there a way to verify the success of a non-empty .ser-file?
- is the .ser-file the only file required for a fault-localization report ? 
- In the source-code it is often referring to `dataFile`/`dataDir` (e.g. [FaultLocalizationReportBuilder](https://github.com/GZoltar/gzoltar/blob/51967a34817d07fb4d2a9f9c6b193be7089b842d/com.gzoltar.report/src/main/java/com/gzoltar/report/fl/FaultLocalizationReportBuilder.java#L33)) , does this always refer to a .ser-file?
- in the [com.gzoltar.cli](https://github.com/GZoltar/gzoltar/blob/51967a34817d07fb4d2a9f9c6b193be7089b842d/com.gzoltar.cli/src/main/java/com/gzoltar/cli/commands/AbstractReport.java#L40) it mentions that the --dataFile must be an `*.exec` - is that a mistake?
- The arguments for the [--buildLocation](https://github.com/GZoltar/gzoltar/blob/51967a34817d07fb4d2a9f9c6b193be7089b842d/com.gzoltar.cli/src/main/java/com/gzoltar/cli/commands/AbstractReport.java#L32) and [--outputDirectory](https://github.com/GZoltar/gzoltar/blob/51967a34817d07fb4d2a9f9c6b193be7089b842d/com.gzoltar.cli/src/main/java/com/gzoltar/cli/commands/AbstractReport.java#L36) have the same description - must they match? 
- Is it correct that for the steps up until including the instrumentation the *vanilla*-classes must be added to the class-path, and in the later steps (runTestMethods & faultLocalization) the instrumented-classes must be added to the class-path? 
- When I succeeded to create a .ser-file for a project I want to analyze, and I started to build a FaultLocalizationReport from the java interface it creates an empty spectrum. I think some agent-configs are missing (especially build-location). Should this build location point to the instrumented java files or the vanilla ones? Are other agent-configs required? 

Apart from that, is the suggested use of gzoltar the CLI ? 
In general I want to use the Gzoltar output in astor directly, but it seems that with the class-path-configuration I might run into more issues. So at the moment my approach would be to run the CLI and just read-in the files, or is *direct use* of the core library encouraged?

**Comment by jose** [comment]
> I have been looking into the shell example starting from the patch in #41, and I think I get most of what is happening.

Great.  Are you planning to use the online or offline mode? Unless you're dealing with, e.g., tests automatically generated by [EvoSuite](https://github.com/EvoSuite/evosuite) which require their own Java Classloader, I would recommend the online mode.

> the instrumentation is done on .class files and .class-files only? Does it need to instrument the tests too?

It does not.  By default, GZoltar instruments every single class that is loaded by the JVM. However you can specify (regex support) which classes are instrumented.  For example, in [here](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.cli.examples/run.sh#L132) GZoltar's Agent is informed to only instrument classes named `org.gzoltar.examples.CharacterCounter` and any subclass of `org.gzoltar.examples.CharacterCounter`.

> is there a way to verify the success of a non-empty .ser-file?

A non-empty .ser file means that classes were instrumented successfully, test executed, and coverage collected.

> is the .ser-file the only file required for a fault-localization report ?

Yes.

> In the source-code it is often referring to dataFile/dataDir (e.g. FaultLocalizationReportBuilder) , does this always refer to a .ser-file?

I failed to find any evidence of `dataDir`.  The `dataFile` in the `FaultLocalizationReportBuilder` class refers to the .ser file, yes.

> in the com.gzoltar.cli it mentions that the --dataFile must be an *.exec - is that a mistake?

Yes, that's a typo, `*.exec` -> `*.ser`.

> The arguments for the --buildLocation and --outputDirectory have the same description - must they match?

They should not.  That's likely a copy-paste typo.  `buildLocation` should point to the directory with all .class files, e.g., `target/classes` and `outputDirectory` is the directory to which the fault localization report will be written.

> Is it correct that for the steps up until including the instrumentation the vanilla-classes must be added to the class-path, and in the later steps (runTestMethods & faultLocalization) the instrumented-classes must be added to the class-path?

Depends whether you're using the online (aka runtime instrumentation) or offline mode.  Online mode, vanilla classes must be added to the classpath at all times.  Offline mode, instrumented-classes must be added to the classpath while executing project's test cases (besides this step, always add vanilla classes to the classpath).

> When I succeeded to create a .ser-file for a project I want to analyze, and I started to build a FaultLocalizationReport from the java interface it creates an empty spectrum. I think some agent-configs are missing (especially build-location). Should this build location point to the instrumented java files or the vanilla ones? Are other agent-configs required?

Once the .ser file is generated you should not need to define any other Agent config. You should only need to define `buildLocation` (which should point to the vanilla ones), `dataFile` (which should point to the .ser file), and `outputDirectory` to be able to generated a fault-localization-report.

> Apart from that, is the suggested use of gzoltar the CLI ?

For Maven-based or Ant-based projects, which you can edit and include GZoltar in the `pom.xml`/`build.xml` file, I recommend one of the many GZoltar's plugins.  In your case, I believe the CLI version is the most suitable one.

> In general I want to use the Gzoltar output in astor directly, but it seems that with the class-path-configuration I might run into more issues. So at the moment my approach would be to run the CLI and just read-in the files, or is direct use of the core library encouraged?

To avoid instrumentations issues, classpaths issues, classloader issues, ..., the use of GZoltar's code via its own Java API is discouraged.


--
Best,
Jose

**Comment by lapplislazuli** [comment]
I think I have made sufficient progress thanks to your great help :)
