### ISSUE TITLE
Fail to run Gzoltar on Closure-90 (Exception in thread "main" java.lang.NoSuchMethodError).

### ISSUE THREAD

**Issue by QuanjunZhang** [GZoltar/gzoltar#46]
**Problem:**
I failed to run the [script](https://github.com/GZoltar/gzoltar/issues/30#issuecomment-706308460) in some bugs (e.g., Closure-90 and later) from defecst4j.
For example, when I ran Closure-90, it would return the follwing error message:
![63961644564064_ pic](https://user-images.githubusercontent.com/19492104/153552252-5f1ef401-d6ec-42bd-988c-b28fc059a14f.jpg)

**Setting:**
The Gzoltar and Defects4j are latest version and java version is jdk1.8.0_212.

**Log:**
The execution logs of Closure-89(success) and 90(fail) are presented.
[Closure-89.log](https://github.com/GZoltar/gzoltar/files/8066272/Closure-89.log)
[Closure-90.log](https://github.com/GZoltar/gzoltar/files/8066273/Closure-90.log)

--
Best,
Echo

**Comment by QuanjunZhang** [comment]
> **Problem:** I failed to run the [script](https://github.com/GZoltar/gzoltar/issues/30#issuecomment-706308460) in some bugs (e.g., Closure-90 and later) from defecst4j. For example, when I ran Closure-90, it would return the follwing error message: ![63961644564064_ pic](https://user-images.githubusercontent.com/19492104/153552252-5f1ef401-d6ec-42bd-988c-b28fc059a14f.jpg)
> 
> **Setting:** The Gzoltar and Defects4j are latest version and java version is jdk1.8.0_212.
> 
> **Log:** The execution logs of Closure-89(success) and 90(fail) are presented. [Closure-89.log](https://github.com/GZoltar/gzoltar/files/8066272/Closure-89.log) [Closure-90.log](https://github.com/GZoltar/gzoltar/files/8066273/Closure-90.log)
> 
> -- Best, Echo

**Comment by jose** [comment]
Hi @QuanjunZhang,

Thanks for reporting this unexpected behaviour.  This error is, usually, either because JUnit is not on the classpath or an old/unsupported version of JUnit is on the classpath.

Assuming you're indeed using [this script](https://github.com/GZoltar/gzoltar/issues/30#issuecomment-706308460), try to replace the following line (under the "Collect unit tests to run GZoltar with' section") and re-run the script.
```bash
$ java -cp "$test_classpath:$test_classes_dir:$D4J_HOME/framework/projects/lib/junit-4.11.jar:$GZOLTAR_CLI_JAR" \
   ...
```
with
```bash
$ java -cp "$D4J_HOME/framework/projects/lib/junit-4.11.jar:$test_classpath:$test_classes_dir:$GZOLTAR_CLI_JAR" \
   ...
```

--
Best,
Jose
