### ISSUE TITLE
How can I get the map between the test and the covered line/method/class from the matrix.txt

### ISSUE THREAD

**Issue by ekincanufuktepe** [GZoltar/gzoltar#56]
Hello,

I am currently using GZoltar CLI to generate my coverage matrix. 

1. I was wondering if there is any way I can find which line/method/class is covered by a test in the `matrix.txt`. For now, I only have a binary matrix and don't know which methods/lines/classes are covered. Can I assume that each row in the `matrix.txt` corresponds to the same row in the `test.csv` file generated by GZoltar, because the number of tests and the rows are the same?

2. I was also curious about the difference between the files `test.csv` and `unit_tests.txt`. Are the tests in `test.csv` not unit tests? It seems like the `unit_tests.txt` has more tests. I worked on the project `Lang` from Defects4J, on the fixed version of bug id 1. GZoltar outputted 489 tests in the `test.csv` file, and 2295 tests in the `unit_tests.txt` file. 

Thanks!

Ekin

**Comment by ekincanufuktepe** [comment]
Hello,

I think I figured out how to acquire the information that I was looking for. I forked GZoltar, and added a few lines where the `matrix.txt` is generated. I just wrote the matrix column and row information to separate files, which I noticed later that I didn't need to write the row information because it is equivalent to the generated `test.csv` file.

Here is my commit [ba4ff448b1d2f46d73ddf69bf419b1e4b00042d5](https://github.com/ekincanufuktepe/gzoltar/commit/ba4ff448b1d2f46d73ddf69bf419b1e4b00042d5) just in case if there is anyone who had the same question that I had. I simply took the shortcut for myself to get the information I am looking for. Feel free to pull or adapt to the changes I did, or make it better than mine!

I am closing this issue, however, if I did anything wrong or want to discuss further on my approach, just let me know!

Ekin

**Comment by ZexingChang** [comment]
Hi:
I have the same problem.  I worked on the project ``Chart`` from ``Defects4J``, on the fixed version of bug id 1. GZoltar outputted 1315 tests in the ``test.csv`` file, but 2201 tests in the ``unit_tests.txt`` file.

How did you solve it?
