### ISSUE TITLE
how can i use gzoltar/utils.sh  in  fault-localization-data

### ISSUE THREAD

**Issue by 87score** [GZoltar/gzoltar#62]
Excuse me, I am a senior student from taiwan. 
I want to learn something about SBFL. 
After reading Fault-localization-data repository in bitbucket,
konw how to collect coverage at line level. 
But I don't know what command to use in the terminal to use [fault-localization-data/gzoltar/utils.sh](https://bitbucket.org/rjust/fault-localization-data/src/master/gzoltar/utils.sh)? 
Another question is,what version of defect4j is [fault-localization-data](http://fault-localization.cs.washington.edu/data/) based on?

**Comment by 87score** [comment]
> Excuse me, I am a senior student from taiwan. I want to learn something about SBFL. After reading Fault-localization-data repository in bitbucket,konw how to collect coverage at line level. But I don't know what command to use in the terminal to use [fault-localization-data/gzoltar/utils.sh](https://bitbucket.org/rjust/fault-localization-data/src/master/gzoltar/utils.sh)? "Another question is,What version of defect4j is [fault-localization-data](http://fault-localization.cs.washington.edu/data/) based on? ? "

**Comment by jose** [comment]
Hi @87score,

> I don't know what command to use in the terminal to use [fault-localization-data/gzoltar/utils.sh](https://bitbucket.org/rjust/fault-localization-data/src/master/gzoltar/utils.sh)?

You're not supposed to use the [`fault-localization-data/gzoltar/utils.sh`](https://bitbucket.org/rjust/fault-localization-data/src/master/gzoltar/utils.sh) script directly from the command line.  That is just a script with some util functions that support the [`fault-localization-data/gzoltar/job.sh`](https://bitbucket.org/rjust/fault-localization-data/src/master/gzoltar/job.sh) script. You should instead use the [`fault-localization-data/gzoltar/job.sh`](https://bitbucket.org/rjust/fault-localization-data/src/master/gzoltar/job.sh) script as, for example:

```bash
bash job.sh --project Chart --bug 1 --output_dir Chart-1 --tool developer
```

> what version of defect4j is [fault-localization-data](http://fault-localization.cs.washington.edu/data/) based on?

v1.4.0

--
Best,
Jose
