### ISSUE TITLE
how to collect coverage at method level ?

### ISSUE THREAD

**Issue by WuYiwen97** [GZoltar/gzoltar#9]
Excuse me,
I am a senior student from China.
I want to learn something about SBFL.
After reading Fault-localization-data repository in bitbucket,I have already konw how to collect coverage at line level.
But I donnot know how to collect coverage at method level.（Because my ability is limited😭）
could you tell me how to....I will be very thankful~

**Comment by jose** [comment]
Hi @WuYiwen97,

GZoltar supports out-of-the-box three granularity levels: `class`, `method`, and `line` (default). To use a different granularity level you must configure the fault-localization report with a different granularity level.

For example:
- Supposing you are using the [Ant example](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.ant.examples) of the [GZoltar Ant task](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.ant) you need to modify line [#134](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.ant.examples/simple/build.xml#L134) to `method`, or `class`.
- Supposing you are using the [GZoltar CLI example](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.cli.examples) you need to modify line [#172](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.cli.examples/run.sh#L172) to `method`, or `class`.
- Supposing you are using the [GZoltar Maven example](https://github.com/GZoltar/gzoltar/tree/master/com.gzoltar.maven.examples) you need to modify line [#81](https://github.com/GZoltar/gzoltar/blob/master/com.gzoltar.maven.examples/pom.xml#L81) to `method`, or `class`.

In case you are using external scripts such the ones in the [fault-localization repository](https://bitbucket.org/rjust/fault-localization-data/src/master/) you need to modify line [#438](https://bitbucket.org/rjust/fault-localization-data/src/6447ffd43178bcb8a08c14a8aaae8ceb59438111/gzoltar/utils.sh#lines-438) to `method`, or `class`. Please not that if you change [#438](https://bitbucket.org/rjust/fault-localization-data/src/6447ffd43178bcb8a08c14a8aaae8ceb59438111/gzoltar/utils.sh#lines-438) to `method`, or `class` you would also have to comment out or remove the sanity checks performed in lines 283 -- 533 in the `job.sh` [script](https://bitbucket.org/rjust/fault-localization-data/src/6447ffd43178bcb8a08c14a8aaae8ceb59438111/gzoltar/job.sh#lines-283).
(the `job.sh` script runs GZoltar on a single D4J bug).


--
Best,
Jose

**Comment by WuYiwen97** [comment]
Wonderful ~Thank you very much ,that is what exactly I want. 😘

**Comment by delsner** [comment]
Just a note on this: on MacOS I had to manually provide the flag `-Dgzoltar.granularity=method`, e.g. `mvn gzoltar:fl-report -Dgzoltar.granularity=method`. Providing the `method` value via the plugin configuration did not work.
